# Generated by Django 6.0.2 on 2026-03-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UPIID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=100, unique=True)),
                ('reported_count', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('fraud', 'Fraud')], default='safe', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
