# Generated by Django 6.0.2 on 2026-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0002_upiid_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upiid',
            name='status',
            field=models.CharField(default='Safe', max_length=20),
        ),
    ]
