# Generated by Django 6.0.2 on 2026-03-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0003_alter_upiid_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upiid',
            options={'ordering': ['-reported_count'], 'verbose_name': 'UPI ID', 'verbose_name_plural': 'UPI IDs'},
        ),
        migrations.AlterField(
            model_name='upiid',
            name='reported_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upiid',
            name='status',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Suspicious', 'Suspicious'), ('Fraud', 'Fraud')], default='Safe', max_length=20),
        ),
        migrations.AlterField(
            model_name='upiid',
            name='upi_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
