# Generated by Django 6.0.1 on 2026-03-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0005_advanced_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transactionsignal',
            new_name='fraud_detec_upi_id_1ee41e_idx',
            old_name='fraud_trans_upi_idx',
        ),
    ]
