# Generated by Django 5.1.4 on 2026-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0003_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_malicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfile',
            name='vt_analysis_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='vt_harmless',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='vt_malicious',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='vt_suspicious',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='vt_undetected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
