# Generated by Django 5.1.4 on 2026-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0004_userfile_is_malicious_userfile_vt_analysis_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
