# Generated by Django 5.2.10 on 2026-02-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0006_userfile_malware_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='file',
        ),
        migrations.AddField(
            model_name='userfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
