# Generated by Django 6.0.3 on 2026-03-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='risk_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='scan_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
