# Generated by Django 6.0.1 on 2026-03-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='risk_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(default='SAFE', max_length=20),
        ),
    ]
